spring:
  application:
    name: @project.artifactId@
  main:
    banner-mode: "off"
  profiles:
    active: local # = console-log; when using spring-cloud-config, active profiles should be defined on the config server only

management:
  endpoints:
    web:
      exposure:
        include: ['*'] # safe as icinga-status starter disables all endpoints except its own ones by default; be careful when not using that starter

stage: local

idealo:
  logging:
    file:
      dir: /tmp/${spring.application.name}/logs
    redis:
      key: non-existant

---
spring:
  profiles: local

stage: local

---
spring:
  profiles: development

stage: development

---
spring:
  profiles: testing

stage: testing

---
spring:
  profiles: staging

stage: staging

---
spring:
  profiles: production

stage: production
